### ISSUE TITLE
Missing NYC county-level data

### ISSUE THREAD

**Issue by WCrawford-Crudell** [xindyhu/covid_risk_score#1]
Zip codes 11216 (Brooklyn zip code) and 11432 (Queens zip code) calculate a risk score of 1. This is because the case count found for these two zip codes is 0. Looking at the NYT data source, the NYC data is aggregated and does not reference a zip code. 
This observation flags two issues in my mind: 
- Missing data for zip codes in NYC
- When a county is recorded as having 0 reported cases, the risk score calculates a risk score of 1. Should risk score be so low when taking into account the under-reporting of cases?

**Comment by xindyhu** [comment]
Thanks Willow. This is addressed. I used a quick fix to provide the overall data for NYC when any zipcode in the five Boroughs are used. We can provide more detailed info but that would require a different data source. Plus the prevalence rates for the 5 Boroughs range from 400-800 per 100,000, not a big difference.
